"use strict";
exports.__esModule = true;
var colors_json_1 = require("@openbricksandbraces/designtokens/dist/json/colors.json");
var typography_json_1 = require("@openbricksandbraces/designtokens/dist/json/typography.json");
var metrics_json_1 = require("@openbricksandbraces/designtokens/dist/json/metrics.json");
var animations_json_1 = require("@openbricksandbraces/designtokens/dist/json/animations.json");
var color_1 = require("color");
var rgba = function (hex, alpha) {
    return (0, color_1["default"])(hex).alpha(alpha !== null && alpha !== void 0 ? alpha : 1);
};
var theme = {
    light: {
        /* " Root Colors " */
        "color-app-01": colors_json_1["default"]["gray-50"],
        "color-app-02": colors_json_1["default"]["gray-200"],
        "color-app-03": colors_json_1["default"]["gray-300"],
        "color-app-04": colors_json_1["default"]["gray-500"],
        "color-app-05": colors_json_1["default"].white,
        "color-app-05-alpha-5": rgba(colors_json_1["default"].white, 0.05),
        "color-app-05-alpha-10": rgba(colors_json_1["default"].white, 0.1),
        "color-app-background": colors_json_1["default"]["gray-50"],
        /* " Background Colors " */
        "color-background": colors_json_1["default"]["gray-100"],
        "color-background-alpha-0": rgba(colors_json_1["default"]["gray-100"], 0),
        "color-hover": colors_json_1["default"]["gray-150"],
        "color-active": colors_json_1["default"]["gray-200"],
        "color-background-light": colors_json_1["default"]["gray-150"],
        "color-hover-light": colors_json_1["default"]["gray-200"],
        "color-active-light": colors_json_1["default"]["gray-250"],
        "color-focus": colors_json_1["default"].white,
        "color-focus-inverse": colors_json_1["default"].black,
        "color-divider-dark": rgba(colors_json_1["default"].black, 0.2),
        "color-divider-light": rgba(colors_json_1["default"].white, 0.2),
        "color-decoration": colors_json_1["default"]["purple-500"],
        "color-selected": colors_json_1["default"]["gray-150"],
        "color-selected-light": colors_json_1["default"]["gray-200"],
        "color-unselected": colors_json_1["default"]["gray-100"],
        "color-readonly": colors_json_1["default"]["gray-100"],
        "color-disabled": colors_json_1["default"]["gray-150"],
        "color-skeleton-01": colors_json_1["default"]["gray-100"],
        "color-skeleton-02": colors_json_1["default"]["gray-150"],
        "color-skeleton-03": colors_json_1["default"]["gray-250"],
        "color-skeleton-04": rgba(colors_json_1["default"]["gray-250"], 0.25),
        /* " Table Colors " */
        "color-table-background": colors_json_1["default"]["gray-100"],
        "color-table-hover": colors_json_1["default"]["gray-200"],
        "color-table-active": colors_json_1["default"]["gray-250"],
        /* " Border Colors " */
        "color-border": colors_json_1["default"]["gray-150"],
        "color-border-light": colors_json_1["default"]["gray-200"],
        /* " Divider Colors " */
        "color-divider-subtle": colors_json_1["default"]["gray-100"],
        "color-divider-default": colors_json_1["default"]["gray-150"],
        "color-divider-harsh": colors_json_1["default"]["gray-300"],
        /* " Font Colors " */
        "color-font-selected": colors_json_1["default"].white,
        "color-font-unselected": colors_json_1["default"]["gray-700"],
        "color-font-text-01": colors_json_1["default"]["gray-950"],
        "color-font-text-02": colors_json_1["default"]["gray-850"],
        "color-font-text-03": colors_json_1["default"]["gray-750"],
        "color-font-text-04": colors_json_1["default"]["gray-650"],
        "color-font-text-05": colors_json_1["default"]["gray-500"],
        "color-font-text-inverse": colors_json_1["default"]["gray-50"],
        "color-font-decoration": colors_json_1["default"]["purple-750"],
        "color-font-link": colors_json_1["default"]["blue-600"],
        "color-font-link-hover": colors_json_1["default"]["blue-700"],
        "color-font-placeholder": colors_json_1["default"]["gray-400"],
        "color-font-readonly": colors_json_1["default"]["gray-650"],
        "color-font-disabled": colors_json_1["default"]["gray-250"],
        "color-font-warning": colors_json_1["default"]["yellow-600"],
        "color-font-success": colors_json_1["default"]["green-600"],
        "color-font-info": colors_json_1["default"]["blue-600"],
        "color-font-danger": colors_json_1["default"]["red-600"],
        /* " Button & Interactive Colors " */
        "color-primary-enabled": colors_json_1["default"]["purple-500"],
        "color-primary-hover": colors_json_1["default"]["purple-450"],
        "color-primary-active": colors_json_1["default"]["purple-400"],
        "color-secondary-enabled": colors_json_1["default"]["gray-300"],
        "color-secondary-hover": colors_json_1["default"]["gray-250"],
        "color-secondary-active": colors_json_1["default"]["gray-200"],
        "color-tertiary-enabled": colors_json_1["default"].white,
        "color-tertiary-hover": colors_json_1["default"]["gray-450"],
        "color-tertiary-active": colors_json_1["default"]["gray-400"],
        "color-ghost-enabled": "transparent",
        "color-ghost-hover": rgba(colors_json_1["default"].white, 0.1),
        "color-ghost-active": rgba(colors_json_1["default"].white, 0.2),
        "color-warning": colors_json_1["default"]["yellow-500"],
        "color-info": colors_json_1["default"]["blue-500"],
        "color-success": colors_json_1["default"]["green-500"],
        "color-danger": colors_json_1["default"]["red-500"],
        "color-danger-hover": colors_json_1["default"]["red-450"],
        "color-danger-active": colors_json_1["default"]["red-400"],
        /* " Badge Colors " */
        "color-badge-gray-bg": colors_json_1["default"]["gray-150"],
        "color-badge-gray-font": colors_json_1["default"]["gray-900"],
        "color-badge-gray-border": colors_json_1["default"]["gray-200"],
        "color-badge-red-bg": colors_json_1["default"]["red-150"],
        "color-badge-red-font": colors_json_1["default"]["red-900"],
        "color-badge-red-border": colors_json_1["default"]["red-200"],
        "color-badge-green-bg": colors_json_1["default"]["green-150"],
        "color-badge-green-font": colors_json_1["default"]["green-900"],
        "color-badge-green-border": colors_json_1["default"]["green-200"],
        "color-badge-yellow-bg": colors_json_1["default"]["yellow-150"],
        "color-badge-yellow-font": colors_json_1["default"]["yellow-900"],
        "color-badge-yellow-border": colors_json_1["default"]["yellow-200"],
        "color-badge-blue-bg": colors_json_1["default"]["blue-150"],
        "color-badge-blue-font": colors_json_1["default"]["blue-900"],
        "color-badge-blue-border": colors_json_1["default"]["blue-200"],
        "color-badge-cyan-bg": colors_json_1["default"]["cyan-150"],
        "color-badge-cyan-font": colors_json_1["default"]["cyan-900"],
        "color-badge-cyan-border": colors_json_1["default"]["cyan-200"],
        "color-badge-orange-bg": colors_json_1["default"]["orange-150"],
        "color-badge-orange-font": colors_json_1["default"]["orange-900"],
        "color-badge-orange-border": colors_json_1["default"]["orange-200"],
        "color-badge-purple-bg": colors_json_1["default"]["purple-150"],
        "color-badge-purple-font": colors_json_1["default"]["purple-900"],
        "color-badge-purple-border": colors_json_1["default"]["purple-200"],
        /* = = = Typography = = = */
        /* " Type Scale " */
        "font-family": typography_json_1["default"]["font-family"],
        "font-family-code": typography_json_1["default"]["font-family-code"],
        /* Learn more under https://css-tricks.com/linearly-scale-font-size-with-css-clamp-based-on-the-viewport/ */
        "font-caption-size": typography_json_1["default"]["font-caption-size"],
        "font-label-size": typography_json_1["default"]["font-label-size"],
        "font-body-01-size": typography_json_1["default"]["font-body-01-size"],
        "font-body-02-size": typography_json_1["default"]["font-body-02-size"],
        "font-headline-01-size": typography_json_1["default"]["font-headline-01-size"],
        "font-headline-02-size": typography_json_1["default"]["font-headline-02-size"],
        "font-headline-03-size": typography_json_1["default"]["font-headline-03-size"],
        "font-headline-04-size": typography_json_1["default"]["font-headline-04-size"],
        "font-headline-05-size": typography_json_1["default"]["font-headline-05-size"],
        "font-headline-06-size": typography_json_1["default"]["font-headline-06-size"],
        "font-marketing-01-size": typography_json_1["default"]["font-marketing-01-size"],
        "font-marketing-02-size": typography_json_1["default"]["font-marketing-02-size"],
        "font-quote-01-size": typography_json_1["default"]["font-quote-01-size"],
        "font-quote-02-size": typography_json_1["default"]["font-quote-02-size"],
        "font-code-size": typography_json_1["default"]["font-code-size"],
        /* " Font weights " */
        "font-caption-weight": typography_json_1["default"]["font-caption-weight"],
        "font-label-weight": typography_json_1["default"]["font-label-weight"],
        "font-body-01-weight": typography_json_1["default"]["font-body-01-weight"],
        "font-body-02-weight": typography_json_1["default"]["font-body-02-weight"],
        "font-headline-01-weight": typography_json_1["default"]["font-headline-01-weight"],
        "font-headline-02-weight": typography_json_1["default"]["font-headline-02-weight"],
        "font-headline-03-weight": typography_json_1["default"]["font-headline-03-weight"],
        "font-headline-04-weight": typography_json_1["default"]["font-headline-04-weight"],
        "font-headline-05-weight": typography_json_1["default"]["font-headline-05-weight"],
        "font-headline-06-weight": typography_json_1["default"]["font-headline-06-weight"],
        "font-marketing-01-weight": typography_json_1["default"]["font-marketing-01-weight"],
        "font-marketing-02-weight": typography_json_1["default"]["font-marketing-02-weight"],
        "font-quote-01-weight": typography_json_1["default"]["font-quote-01-weight"],
        "font-quote-02-weight": typography_json_1["default"]["font-quote-02-weight"],
        "font-code-weight": typography_json_1["default"]["font-code-weight"],
        /* " Font styles " */
        "font-caption-style": typography_json_1["default"]["font-caption-style"],
        "font-label-style": typography_json_1["default"]["font-label-style"],
        "font-body-01-style": typography_json_1["default"]["font-body-01-style"],
        "font-body-02-style": typography_json_1["default"]["font-body-02-style"],
        "font-headline-01-style": typography_json_1["default"]["font-headline-01-style"],
        "font-headline-02-style": typography_json_1["default"]["font-headline-02-style"],
        "font-headline-03-style": typography_json_1["default"]["font-headline-03-style"],
        "font-headline-04-style": typography_json_1["default"]["font-headline-04-style"],
        "font-headline-05-style": typography_json_1["default"]["font-headline-05-style"],
        "font-headline-06-style": typography_json_1["default"]["font-headline-06-style"],
        "font-marketing-01-style": typography_json_1["default"]["font-marketing-01-style"],
        "font-marketing-02-style": typography_json_1["default"]["font-marketing-02-style"],
        "font-quote-01-style": typography_json_1["default"]["font-quote-01-style"],
        "font-quote-02-style": typography_json_1["default"]["font-quote-02-style"],
        "font-code-style": typography_json_1["default"]["font-code-style"],
        /* " Line heights " */
        "font-caption-leading": typography_json_1["default"]["font-caption-leading"],
        "font-label-leading": typography_json_1["default"]["font-label-leading"],
        "font-body-01-leading": typography_json_1["default"]["font-body-01-leading"],
        "font-body-02-leading": typography_json_1["default"]["font-body-02-leading"],
        "font-headline-01-leading": typography_json_1["default"]["font-headline-01-leading"],
        "font-headline-02-leading": typography_json_1["default"]["font-headline-02-leading"],
        "font-headline-03-leading": typography_json_1["default"]["font-headline-03-leading"],
        "font-headline-04-leading": typography_json_1["default"]["font-headline-04-leading"],
        "font-headline-05-leading": typography_json_1["default"]["font-headline-05-leading"],
        "font-headline-06-leading": typography_json_1["default"]["font-headline-06-leading"],
        "font-marketing-01-leading": typography_json_1["default"]["font-marketing-01-leading"],
        "font-marketing-02-leading": typography_json_1["default"]["font-marketing-02-leading"],
        "font-quote-01-leading": typography_json_1["default"]["font-quote-01-leading"],
        "font-quote-02-leading": typography_json_1["default"]["font-quote-02-leading"],
        "font-code-leading": typography_json_1["default"]["font-code-leading"],
        /* = = = Sizes = = = */
        /* " Container Sizes " */
        "size-container-01": metrics_json_1["default"]["container-01"],
        "size-container-02": metrics_json_1["default"]["container-02"],
        "size-container-03": metrics_json_1["default"]["container-03"],
        "size-container-04": metrics_json_1["default"]["container-04"],
        "size-container-05": metrics_json_1["default"]["container-05"],
        "size-container-06": metrics_json_1["default"]["container-06"],
        "size-container-07": metrics_json_1["default"]["container-07"],
        "size-container-08": metrics_json_1["default"]["container-08"],
        /* " Field Sizes " */
        "size-field-xsmall": metrics_json_1["default"]["field-xsmall"],
        "size-field-small": metrics_json_1["default"]["field-small"],
        "size-field-default": metrics_json_1["default"]["field-default"],
        "size-field-large": metrics_json_1["default"]["field-large"],
        /* " Spacing Sizes " */
        "size-spacing-01": metrics_json_1["default"]["spacing-01"],
        "size-spacing-02": metrics_json_1["default"]["spacing-02"],
        "size-spacing-03": metrics_json_1["default"]["spacing-03"],
        "size-spacing-04": metrics_json_1["default"]["spacing-04"],
        "size-spacing-05": metrics_json_1["default"]["spacing-05"],
        "size-spacing-06": metrics_json_1["default"]["spacing-06"],
        "size-spacing-07": metrics_json_1["default"]["spacing-07"],
        "size-spacing-08": metrics_json_1["default"]["spacing-08"],
        "size-spacing-09": metrics_json_1["default"]["spacing-09"],
        "size-spacing-10": metrics_json_1["default"]["spacing-10"],
        "size-spacing-11": metrics_json_1["default"]["spacing-11"],
        "size-spacing-12": metrics_json_1["default"]["spacing-12"],
        "size-spacing-13": metrics_json_1["default"]["spacing-13"],
        /* = = = Component = = = */
        /* " Border Radius " */
        "component-radius-subtle": metrics_json_1["default"]["radius-subtle"],
        "component-radius-default": metrics_json_1["default"]["radius-default"],
        "component-radius-harsh": metrics_json_1["default"]["radius-harsh"],
        /* " Component Inside Padding " */
        "component-padding-inside": metrics_json_1["default"]["padding-inside"],
        /* " Box Shadow " */
        "component-shadow-subtle": metrics_json_1["default"]["shadow-subtle"],
        "component-shadow-default": metrics_json_1["default"]["shadow-default"],
        "component-shadow-harsh": metrics_json_1["default"]["shadow-harsh"],
        /* " Overlay " */
        "component-overlay": metrics_json_1["default"].overlay,
        /* = = = Transitions = = = */
        /* " Static Transitions " */
        "transition-app-01": animations_json_1["default"]["transition-app-01"],
        "transition-app-02": animations_json_1["default"]["transition-app-02"],
        "transition-app-03": animations_json_1["default"]["transition-app-03"],
        "transition-app-04": animations_json_1["default"]["transition-app-04"],
        "transition-app-05": animations_json_1["default"]["transition-app-05"]
    },
    dark: {
        /* " Root Colors " */
        "color-app-01": colors_json_1["default"]["gray-50"],
        "color-app-02": colors_json_1["default"]["gray-200"],
        "color-app-03": colors_json_1["default"]["gray-300"],
        "color-app-04": colors_json_1["default"]["gray-500"],
        "color-app-05": colors_json_1["default"].white,
        "color-app-05-alpha-5": rgba(colors_json_1["default"].white, 0.05),
        "color-app-05-alpha-10": rgba(colors_json_1["default"].white, 0.1),
        "color-app-background": colors_json_1["default"]["gray-50"],
        /* " Background Colors " */
        "color-background": colors_json_1["default"]["gray-100"],
        "color-background-alpha-0": rgba(colors_json_1["default"]["gray-100"], 0),
        "color-hover": colors_json_1["default"]["gray-150"],
        "color-active": colors_json_1["default"]["gray-200"],
        "color-background-light": colors_json_1["default"]["gray-150"],
        "color-hover-light": colors_json_1["default"]["gray-200"],
        "color-active-light": colors_json_1["default"]["gray-250"],
        "color-focus": colors_json_1["default"].white,
        "color-focus-inverse": colors_json_1["default"].black,
        "color-divider-dark": rgba(colors_json_1["default"].black, 0.2),
        "color-divider-light": rgba(colors_json_1["default"].white, 0.2),
        "color-decoration": colors_json_1["default"]["purple-500"],
        "color-selected": colors_json_1["default"]["gray-150"],
        "color-selected-light": colors_json_1["default"]["gray-200"],
        "color-unselected": colors_json_1["default"]["gray-100"],
        "color-readonly": colors_json_1["default"]["gray-100"],
        "color-disabled": colors_json_1["default"]["gray-150"],
        "color-skeleton-01": colors_json_1["default"]["gray-100"],
        "color-skeleton-02": colors_json_1["default"]["gray-150"],
        "color-skeleton-03": colors_json_1["default"]["gray-250"],
        "color-skeleton-04": rgba(colors_json_1["default"]["gray-250"], 0.25),
        /* " Table Colors " */
        "color-table-background": colors_json_1["default"]["gray-100"],
        "color-table-hover": colors_json_1["default"]["gray-200"],
        "color-table-active": colors_json_1["default"]["gray-250"],
        /* " Border Colors " */
        "color-border": colors_json_1["default"]["gray-150"],
        "color-border-light": colors_json_1["default"]["gray-200"],
        /* " Divider Colors " */
        "color-divider-subtle": colors_json_1["default"]["gray-100"],
        "color-divider-default": colors_json_1["default"]["gray-150"],
        "color-divider-harsh": colors_json_1["default"]["gray-300"],
        /* " Font Colors " */
        "color-font-selected": colors_json_1["default"].white,
        "color-font-unselected": colors_json_1["default"]["gray-700"],
        "color-font-text-01": colors_json_1["default"]["gray-950"],
        "color-font-text-02": colors_json_1["default"]["gray-850"],
        "color-font-text-03": colors_json_1["default"]["gray-750"],
        "color-font-text-04": colors_json_1["default"]["gray-650"],
        "color-font-text-05": colors_json_1["default"]["gray-500"],
        "color-font-text-inverse": colors_json_1["default"]["gray-50"],
        "color-font-decoration": colors_json_1["default"]["purple-750"],
        "color-font-link": colors_json_1["default"]["blue-600"],
        "color-font-link-hover": colors_json_1["default"]["blue-700"],
        "color-font-placeholder": colors_json_1["default"]["gray-400"],
        "color-font-readonly": colors_json_1["default"]["gray-650"],
        "color-font-disabled": colors_json_1["default"]["gray-250"],
        "color-font-warning": colors_json_1["default"]["yellow-600"],
        "color-font-success": colors_json_1["default"]["green-600"],
        "color-font-info": colors_json_1["default"]["blue-600"],
        "color-font-danger": colors_json_1["default"]["red-600"],
        /* " Button & Interactive Colors " */
        "color-primary-enabled": colors_json_1["default"]["purple-500"],
        "color-primary-hover": colors_json_1["default"]["purple-450"],
        "color-primary-active": colors_json_1["default"]["purple-400"],
        "color-secondary-enabled": colors_json_1["default"]["gray-300"],
        "color-secondary-hover": colors_json_1["default"]["gray-250"],
        "color-secondary-active": colors_json_1["default"]["gray-200"],
        "color-tertiary-enabled": colors_json_1["default"].white,
        "color-tertiary-hover": colors_json_1["default"]["gray-450"],
        "color-tertiary-active": colors_json_1["default"]["gray-400"],
        "color-ghost-enabled": "transparent",
        "color-ghost-hover": rgba(colors_json_1["default"].white, 0.1),
        "color-ghost-active": rgba(colors_json_1["default"].white, 0.2),
        "color-warning": colors_json_1["default"]["yellow-500"],
        "color-info": colors_json_1["default"]["blue-500"],
        "color-success": colors_json_1["default"]["green-500"],
        "color-danger": colors_json_1["default"]["red-500"],
        "color-danger-hover": colors_json_1["default"]["red-450"],
        "color-danger-active": colors_json_1["default"]["red-400"],
        /* " Badge Colors " */
        "color-badge-gray-bg": colors_json_1["default"]["gray-150"],
        "color-badge-gray-font": colors_json_1["default"]["gray-900"],
        "color-badge-gray-border": colors_json_1["default"]["gray-200"],
        "color-badge-red-bg": colors_json_1["default"]["red-150"],
        "color-badge-red-font": colors_json_1["default"]["red-900"],
        "color-badge-red-border": colors_json_1["default"]["red-200"],
        "color-badge-green-bg": colors_json_1["default"]["green-150"],
        "color-badge-green-font": colors_json_1["default"]["green-900"],
        "color-badge-green-border": colors_json_1["default"]["green-200"],
        "color-badge-yellow-bg": colors_json_1["default"]["yellow-150"],
        "color-badge-yellow-font": colors_json_1["default"]["yellow-900"],
        "color-badge-yellow-border": colors_json_1["default"]["yellow-200"],
        "color-badge-blue-bg": colors_json_1["default"]["blue-150"],
        "color-badge-blue-font": colors_json_1["default"]["blue-900"],
        "color-badge-blue-border": colors_json_1["default"]["blue-200"],
        "color-badge-cyan-bg": colors_json_1["default"]["cyan-150"],
        "color-badge-cyan-font": colors_json_1["default"]["cyan-900"],
        "color-badge-cyan-border": colors_json_1["default"]["cyan-200"],
        "color-badge-orange-bg": colors_json_1["default"]["orange-150"],
        "color-badge-orange-font": colors_json_1["default"]["orange-900"],
        "color-badge-orange-border": colors_json_1["default"]["orange-200"],
        "color-badge-purple-bg": colors_json_1["default"]["purple-150"],
        "color-badge-purple-font": colors_json_1["default"]["purple-900"],
        "color-badge-purple-border": colors_json_1["default"]["purple-200"],
        /* = = = Typography = = = */
        /* " Type Scale " */
        "font-family": typography_json_1["default"]["font-family"],
        "font-family-code": typography_json_1["default"]["font-family-code"],
        /* Learn more under https://css-tricks.com/linearly-scale-font-size-with-css-clamp-based-on-the-viewport/ */
        "font-caption-size": typography_json_1["default"]["font-caption-size"],
        "font-label-size": typography_json_1["default"]["font-label-size"],
        "font-body-01-size": typography_json_1["default"]["font-body-01-size"],
        "font-body-02-size": typography_json_1["default"]["font-body-02-size"],
        "font-headline-01-size": typography_json_1["default"]["font-headline-01-size"],
        "font-headline-02-size": typography_json_1["default"]["font-headline-02-size"],
        "font-headline-03-size": typography_json_1["default"]["font-headline-03-size"],
        "font-headline-04-size": typography_json_1["default"]["font-headline-04-size"],
        "font-headline-05-size": typography_json_1["default"]["font-headline-05-size"],
        "font-headline-06-size": typography_json_1["default"]["font-headline-06-size"],
        "font-marketing-01-size": typography_json_1["default"]["font-marketing-01-size"],
        "font-marketing-02-size": typography_json_1["default"]["font-marketing-02-size"],
        "font-quote-01-size": typography_json_1["default"]["font-quote-01-size"],
        "font-quote-02-size": typography_json_1["default"]["font-quote-02-size"],
        "font-code-size": typography_json_1["default"]["font-code-size"],
        /* " Font weights " */
        "font-caption-weight": typography_json_1["default"]["font-caption-weight"],
        "font-label-weight": typography_json_1["default"]["font-label-weight"],
        "font-body-01-weight": typography_json_1["default"]["font-body-01-weight"],
        "font-body-02-weight": typography_json_1["default"]["font-body-02-weight"],
        "font-headline-01-weight": typography_json_1["default"]["font-headline-01-weight"],
        "font-headline-02-weight": typography_json_1["default"]["font-headline-02-weight"],
        "font-headline-03-weight": typography_json_1["default"]["font-headline-03-weight"],
        "font-headline-04-weight": typography_json_1["default"]["font-headline-04-weight"],
        "font-headline-05-weight": typography_json_1["default"]["font-headline-05-weight"],
        "font-headline-06-weight": typography_json_1["default"]["font-headline-06-weight"],
        "font-marketing-01-weight": typography_json_1["default"]["font-marketing-01-weight"],
        "font-marketing-02-weight": typography_json_1["default"]["font-marketing-02-weight"],
        "font-quote-01-weight": typography_json_1["default"]["font-quote-01-weight"],
        "font-quote-02-weight": typography_json_1["default"]["font-quote-02-weight"],
        "font-code-weight": typography_json_1["default"]["font-code-weight"],
        /* " Font styles " */
        "font-caption-style": typography_json_1["default"]["font-caption-style"],
        "font-label-style": typography_json_1["default"]["font-label-style"],
        "font-body-01-style": typography_json_1["default"]["font-body-01-style"],
        "font-body-02-style": typography_json_1["default"]["font-body-02-style"],
        "font-headline-01-style": typography_json_1["default"]["font-headline-01-style"],
        "font-headline-02-style": typography_json_1["default"]["font-headline-02-style"],
        "font-headline-03-style": typography_json_1["default"]["font-headline-03-style"],
        "font-headline-04-style": typography_json_1["default"]["font-headline-04-style"],
        "font-headline-05-style": typography_json_1["default"]["font-headline-05-style"],
        "font-headline-06-style": typography_json_1["default"]["font-headline-06-style"],
        "font-marketing-01-style": typography_json_1["default"]["font-marketing-01-style"],
        "font-marketing-02-style": typography_json_1["default"]["font-marketing-02-style"],
        "font-quote-01-style": typography_json_1["default"]["font-quote-01-style"],
        "font-quote-02-style": typography_json_1["default"]["font-quote-02-style"],
        "font-code-style": typography_json_1["default"]["font-code-style"],
        /* " Line heights " */
        "font-caption-leading": typography_json_1["default"]["font-caption-leading"],
        "font-label-leading": typography_json_1["default"]["font-label-leading"],
        "font-body-01-leading": typography_json_1["default"]["font-body-01-leading"],
        "font-body-02-leading": typography_json_1["default"]["font-body-02-leading"],
        "font-headline-01-leading": typography_json_1["default"]["font-headline-01-leading"],
        "font-headline-02-leading": typography_json_1["default"]["font-headline-02-leading"],
        "font-headline-03-leading": typography_json_1["default"]["font-headline-03-leading"],
        "font-headline-04-leading": typography_json_1["default"]["font-headline-04-leading"],
        "font-headline-05-leading": typography_json_1["default"]["font-headline-05-leading"],
        "font-headline-06-leading": typography_json_1["default"]["font-headline-06-leading"],
        "font-marketing-01-leading": typography_json_1["default"]["font-marketing-01-leading"],
        "font-marketing-02-leading": typography_json_1["default"]["font-marketing-02-leading"],
        "font-quote-01-leading": typography_json_1["default"]["font-quote-01-leading"],
        "font-quote-02-leading": typography_json_1["default"]["font-quote-02-leading"],
        "font-code-leading": typography_json_1["default"]["font-code-leading"],
        /* = = = Sizes = = = */
        /* " Container Sizes " */
        "size-container-01": metrics_json_1["default"]["container-01"],
        "size-container-02": metrics_json_1["default"]["container-02"],
        "size-container-03": metrics_json_1["default"]["container-03"],
        "size-container-04": metrics_json_1["default"]["container-04"],
        "size-container-05": metrics_json_1["default"]["container-05"],
        "size-container-06": metrics_json_1["default"]["container-06"],
        "size-container-07": metrics_json_1["default"]["container-07"],
        "size-container-08": metrics_json_1["default"]["container-08"],
        /* " Field Sizes " */
        "size-field-xsmall": metrics_json_1["default"]["field-xsmall"],
        "size-field-small": metrics_json_1["default"]["field-small"],
        "size-field-default": metrics_json_1["default"]["field-default"],
        "size-field-large": metrics_json_1["default"]["field-large"],
        /* " Spacing Sizes " */
        "size-spacing-01": metrics_json_1["default"]["spacing-01"],
        "size-spacing-02": metrics_json_1["default"]["spacing-02"],
        "size-spacing-03": metrics_json_1["default"]["spacing-03"],
        "size-spacing-04": metrics_json_1["default"]["spacing-04"],
        "size-spacing-05": metrics_json_1["default"]["spacing-05"],
        "size-spacing-06": metrics_json_1["default"]["spacing-06"],
        "size-spacing-07": metrics_json_1["default"]["spacing-07"],
        "size-spacing-08": metrics_json_1["default"]["spacing-08"],
        "size-spacing-09": metrics_json_1["default"]["spacing-09"],
        "size-spacing-10": metrics_json_1["default"]["spacing-10"],
        "size-spacing-11": metrics_json_1["default"]["spacing-11"],
        "size-spacing-12": metrics_json_1["default"]["spacing-12"],
        "size-spacing-13": metrics_json_1["default"]["spacing-13"],
        /* = = = Component = = = */
        /* " Border Radius " */
        "component-radius-subtle": metrics_json_1["default"]["radius-subtle"],
        "component-radius-default": metrics_json_1["default"]["radius-default"],
        "component-radius-harsh": metrics_json_1["default"]["radius-harsh"],
        /* " Component Inside Padding " */
        "component-padding-inside": metrics_json_1["default"]["padding-inside"],
        /* " Box Shadow " */
        "component-shadow-subtle": metrics_json_1["default"]["shadow-subtle"],
        "component-shadow-default": metrics_json_1["default"]["shadow-default"],
        "component-shadow-harsh": metrics_json_1["default"]["shadow-harsh"],
        /* " Overlay " */
        "component-overlay": metrics_json_1["default"].overlay,
        /* = = = Transitions = = = */
        /* " Static Transitions " */
        "transition-app-01": animations_json_1["default"]["transition-app-01"],
        "transition-app-02": animations_json_1["default"]["transition-app-02"],
        "transition-app-03": animations_json_1["default"]["transition-app-03"],
        "transition-app-04": animations_json_1["default"]["transition-app-04"],
        "transition-app-05": animations_json_1["default"]["transition-app-05"]
    }
};
exports["default"] = theme;
